### ISSUE TITLE
wrong speed grade

### ISSUE THREAD

**Issue by l3est** [alexzaworski/PageSpeed-Badges#3]
I get 99-100 from both pagespeed and gtmetrix sites. but this api gives my website 85 for mobile and 95 for desktop.
does it still work?

https://api.speedbadge.io/v1?url=codekhoda.com
website: https://codekhoda.com

can you add cached version of this api? it slows down the website.

**Comment by alexzaworski** [comment]
Hi Mahdi,

The discrepancy may be due to using the old pagespeed API rather than the new lighthouse-based one (google's pagespeed tool uses lighthouse now).

I have a fork of this that I was porting to lighthouse but got busy, you know how it goes ¯\\\_(ツ)_/¯
